name: branch
description: "blackforest_stockorder"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  mobile_scanner: ^5.1.1
  cached_network_image: ^3.4.1
  esc_pos_printer: ^4.1.0
  esc_pos_utils: ^1.1.0
  network_info_plus: ^4.0.2
  camera: ^0.10.6  # For live camera capture
  permission_handler: ^11.3.1  # For requesting camera permissions
  image: ^3.3.0  # For image compression
  path_provider: ^2.1.3  # For temp file storage
  intl: ^0.18.1
  qr_flutter: ^4.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


